import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export async function Dashboard() {
  const supabase = await createClient();
  const [{ data: projects }, { data: tasks }, { data: activity }, { data: attention }] = await Promise.all([
    supabase.from("projects").select("id, name, status").order("updated_at", { ascending: false }).limit(6),
    supabase.from("tasks").select("id, task_what, task_state, project_id, projects(name)").order("updated_at", { ascending: false }),
    supabase.from("activity_feed").select("id, summary, created_at, users_profile(display_name)").order("created_at", { ascending: false }).limit(8),
    supabase.from("attention_notes").select("id, body, is_resolved, created_at, users_profile(display_name)").eq("is_resolved", false).order("created_at", { ascending: false }).limit(5),
  ]);
  const counts = { todo: tasks?.filter((task) => task.task_state === "todo").length || 0, running: tasks?.filter((task) => task.task_state === "running").length || 0, done: tasks?.filter((task) => task.task_state === "done").length || 0 };
  return <main className="content"><div className="heading"><div><span className="mono">Workspace / Home</span><h1>Team activity</h1><p>See the latest work across your active projects.</p></div><Link className="primary" href="/projects">View projects</Link></div><section className="stat-grid"><div className="stat"><span>Todo</span><strong>{counts.todo}</strong><small className="warning">Tasks waiting to start</small></div><div className="stat"><span>Running</span><strong>{counts.running}</strong><small>Tasks in progress</small></div><div className="stat"><span>Done</span><strong>{counts.done}</strong><small>Completed tasks</small></div><div className="stat"><span>Projects</span><strong>{projects?.length || 0}</strong><small>Active workspace projects</small></div></section><section className="dashboard-grid"><div><div className="panel-title"><h2>Recent activity</h2></div><div className="activity-list">{activity?.length ? activity.map((item) => <div className="activity" key={item.id}><div className="avatar">{String(item.users_profile?.[0]?.display_name || "TM").slice(0, 2).toUpperCase()}</div><p><b>{item.users_profile?.[0]?.display_name || "Team member"}</b> {item.summary}</p><time>{new Date(item.created_at).toLocaleDateString()}</time></div>) : <p className="empty-state">Team activity will appear here as work is created and updated.</p>}</div></div><div><div className="panel-title"><h2>Attention</h2><Link href="/attention">View all</Link></div><div className="deadline-list">{attention?.length ? attention.map((note) => <div className="deadline" key={note.id}><i className="critical" /><div><b>{note.users_profile?.[0]?.display_name || "Team member"}</b><span>{note.body}</span></div></div>) : <p className="empty-state">Nothing needs attention.</p>}</div></div></section><section className="projects"><div className="panel-title"><h2>Recent task records</h2><Link href="/projects">View projects</Link></div>{tasks?.length ? <table><thead><tr><th>Task</th><th>Project</th><th>Status</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><b>{task.task_what}</b></td><td>{task.projects?.[0]?.name || "Project"}</td><td><span className={`status ${task.task_state}`}>{task.task_state}</span></td></tr>)}</tbody></table> : <p className="empty-state">No task records yet.</p>}</section></main>;
}