-- Meridian v1 core. Apply with `supabase db push` after linking this repository.
create extension if not exists "pgcrypto";
create extension if not exists "pg_trgm";
create extension if not exists "vector";

create type public.workspace_role as enum ('owner','admin','member','guest');
create type public.project_status as enum ('planning','active','on_hold','completed','archived');
create type public.project_role as enum ('lead','contributor','viewer');
create type public.task_status as enum ('backlog','todo','in_progress','in_review','done','blocked');
create type public.task_priority as enum ('low','medium','high','urgent');
create type public.material_type as enum ('paper','pdf','note','transcript','dataset','recording','field_note','report','other');
create type public.material_status as enum ('draft','in_review','final','archived');

create table public.users_profile (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username = lower(username) and username ~ '^[a-z0-9._-]{3,40}$'),
  display_name text not null, avatar_url text, role public.workspace_role not null default 'member', title text,
  is_active boolean not null default true, must_change_pw boolean not null default true, last_seen_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.workspace_settings (id int primary key default 1 check (id=1), workspace_name text not null default 'Meridian', logo_url text, theme_overrides jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
insert into public.workspace_settings (id) values (1) on conflict do nothing;

create table public.projects (id uuid primary key default gen_random_uuid(), name text not null, description text, status public.project_status not null default 'planning', color_tag text, start_date date, target_end_date date, owner_id uuid not null references public.users_profile(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.project_members (project_id uuid references public.projects(id) on delete cascade, user_id uuid references public.users_profile(id) on delete cascade, project_role public.project_role not null default 'contributor', created_at timestamptz not null default now(), primary key(project_id,user_id));
create table public.milestones (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null, due_date date, status public.task_status not null default 'todo', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, milestone_id uuid references public.milestones(id) on delete set null, parent_task_id uuid references public.tasks(id) on delete cascade, title text not null, description text, status public.task_status not null default 'backlog', priority public.task_priority not null default 'medium', assignee_id uuid references public.users_profile(id) on delete set null, due_date date, start_date date, estimate_hours numeric(7,2), position int not null default 0, created_by uuid references public.users_profile(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.task_dependencies (task_id uuid references public.tasks(id) on delete cascade, depends_on_task_id uuid references public.tasks(id) on delete cascade, primary key(task_id,depends_on_task_id), check(task_id <> depends_on_task_id));

create table public.materials (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, type public.material_type not null, title text not null, description text, storage_path text, file_size_bytes bigint, mime_type text, status public.material_status not null default 'draft', is_restricted boolean not null default false, researcher_id uuid references public.users_profile(id), collected_date date, source_url text, content_tsv tsvector, embedding vector(1536), created_by uuid references public.users_profile(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index materials_search_idx on public.materials using gin(content_tsv); create index materials_embedding_idx on public.materials using ivfflat(embedding vector_cosine_ops) with (lists=100);
create table public.material_versions (id uuid primary key default gen_random_uuid(), material_id uuid not null references public.materials(id) on delete cascade, version_number int not null, storage_path text, note_body_snapshot jsonb, changed_by uuid references public.users_profile(id), change_summary text, created_at timestamptz not null default now(), unique(material_id,version_number));
create table public.material_shares (material_id uuid references public.materials(id) on delete cascade, user_id uuid references public.users_profile(id) on delete cascade, created_at timestamptz not null default now(), primary key(material_id,user_id));
create table public.tags (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete cascade, label text not null, color text, unique(project_id,label));
create table public.material_tags (material_id uuid references public.materials(id) on delete cascade, tag_id uuid references public.tags(id) on delete cascade, primary key(material_id,tag_id));
create table public.taxonomies (id uuid primary key default gen_random_uuid(), name text not null unique, created_at timestamptz not null default now());
create table public.taxonomy_terms (id uuid primary key default gen_random_uuid(), taxonomy_id uuid not null references public.taxonomies(id) on delete cascade, label text not null, parent_term_id uuid references public.taxonomy_terms(id) on delete set null, unique(taxonomy_id,label));
create table public.material_taxonomy_terms (material_id uuid references public.materials(id) on delete cascade, term_id uuid references public.taxonomy_terms(id) on delete cascade, primary key(material_id,term_id));
create table public.annotations (id uuid primary key default gen_random_uuid(), material_id uuid not null references public.materials(id) on delete cascade, page_number int, rect_coords jsonb, highlighted_text text, comment_body text, author_id uuid not null references public.users_profile(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.notes (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null, body_yjs_state bytea, body_plain_tsv tsvector, linked_material_ids uuid[] not null default '{}', is_restricted boolean not null default false, created_by uuid references public.users_profile(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.references (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, doi text, bibtex_raw text, csl_json jsonb, title text not null, authors jsonb not null default '[]', year int, container_title text, url text, material_id uuid references public.materials(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,doi));
create table public.reference_collections (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table public.reference_collection_items (collection_id uuid references public.reference_collections(id) on delete cascade, reference_id uuid references public.references(id) on delete cascade, primary key(collection_id,reference_id));
create table public.reports (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null, body_richtext jsonb not null default '{}'::jsonb, generated_by uuid references public.users_profile(id), is_shared_externally boolean not null default false, share_token text unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.citations_in_use (id uuid primary key default gen_random_uuid(), reference_id uuid not null references public.references(id) on delete cascade, note_id uuid references public.notes(id) on delete cascade, report_id uuid references public.reports(id) on delete cascade, locator_text text, check (note_id is not null or report_id is not null));

create table public.comments (id uuid primary key default gen_random_uuid(), entity_type text not null check(entity_type in ('material','note','task','report')), entity_id uuid not null, parent_comment_id uuid references public.comments(id) on delete cascade, author_id uuid not null references public.users_profile(id), body text not null, mentions uuid[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.activity_feed (id uuid primary key default gen_random_uuid(), actor_id uuid references public.users_profile(id), verb text not null, entity_type text not null, entity_id uuid, project_id uuid references public.projects(id) on delete cascade, summary text not null, created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), recipient_id uuid not null references public.users_profile(id) on delete cascade, activity_id uuid references public.activity_feed(id) on delete cascade, is_read boolean not null default false, read_at timestamptz, created_at timestamptz not null default now());
create table public.audit_log (id uuid primary key default gen_random_uuid(), actor_id uuid references public.users_profile(id), action text not null, entity_type text not null, entity_id uuid, before_state jsonb, after_state jsonb, ip_address inet, created_at timestamptz not null default now());
create table public.integration_connections (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users_profile(id) on delete cascade, provider text not null check(provider in ('google_drive','slack','zotero','calendar')), access_token_encrypted text, refresh_token_encrypted text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(user_id,provider));
create table public.webhooks (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, target_url text not null, event_types text[] not null, secret text not null, created_at timestamptz not null default now());

create or replace function public.is_admin_or_owner() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.users_profile where id=auth.uid() and role in ('owner','admin') and is_active) $$;
create or replace function public.is_project_member(p_project_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_admin_or_owner() or exists(select 1 from public.project_members where project_id=p_project_id and user_id=auth.uid()) $$;
create or replace function public.can_view_material(p_material_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.materials m where m.id=p_material_id and public.is_project_member(m.project_id) and (not m.is_restricted or public.is_admin_or_owner() or exists(select 1 from public.material_shares s where s.material_id=m.id and s.user_id=auth.uid()))) $$;

alter table public.users_profile enable row level security; alter table public.workspace_settings enable row level security; alter table public.projects enable row level security; alter table public.project_members enable row level security; alter table public.milestones enable row level security; alter table public.tasks enable row level security; alter table public.materials enable row level security; alter table public.notes enable row level security; alter table public.references enable row level security; alter table public.reports enable row level security; alter table public.annotations enable row level security; alter table public.notifications enable row level security; alter table public.activity_feed enable row level security; alter table public.audit_log enable row level security;
create policy "profiles readable to authenticated" on public.users_profile for select to authenticated using (true);
create policy "profile self update" on public.users_profile for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "admins manage profiles" on public.users_profile for all to authenticated using(public.is_admin_or_owner()) with check(public.is_admin_or_owner());
create policy "settings readable" on public.workspace_settings for select to authenticated using(true); create policy "admins manage settings" on public.workspace_settings for all to authenticated using(public.is_admin_or_owner()) with check(public.is_admin_or_owner());
create policy "project visibility" on public.projects for select to authenticated using(public.is_project_member(id)); create policy "admins create projects" on public.projects for insert to authenticated with check(public.is_admin_or_owner()); create policy "project leads update" on public.projects for update to authenticated using(public.is_admin_or_owner() or exists(select 1 from public.project_members pm where pm.project_id=id and pm.user_id=auth.uid() and pm.project_role='lead'));
create policy "members visible" on public.project_members for select to authenticated using(public.is_project_member(project_id)); create policy "admins manage members" on public.project_members for all to authenticated using(public.is_admin_or_owner()) with check(public.is_admin_or_owner());
create policy "tasks by membership" on public.tasks for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id));
create policy "milestones by membership" on public.milestones for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id));
create policy "material visibility" on public.materials for select to authenticated using(public.can_view_material(id)); create policy "material writes by member" on public.materials for insert to authenticated with check(public.is_project_member(project_id)); create policy "material updates by member" on public.materials for update to authenticated using(public.can_view_material(id)) with check(public.is_project_member(project_id));
create policy "notes by membership" on public.notes for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id)); create policy "references by membership" on public.references for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id)); create policy "reports by membership" on public.reports for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id)); create policy "annotations visible with material" on public.annotations for all to authenticated using(public.can_view_material(material_id)) with check(public.can_view_material(material_id));
create policy "own notifications" on public.notifications for all to authenticated using(recipient_id=auth.uid()) with check(recipient_id=auth.uid()); create policy "activity by membership" on public.activity_feed for select to authenticated using(public.is_project_member(project_id)); create policy "audit admin read" on public.audit_log for select to authenticated using(public.is_admin_or_owner());
