-- Complete default-deny RLS coverage for every Meridian business table.
create or replace function public.can_view_comment(p_entity_type text, p_entity_id uuid) returns boolean language sql stable security definer set search_path=public as $$
  select case p_entity_type
    when 'material' then public.can_view_material(p_entity_id)
    when 'note' then exists(select 1 from public.notes n where n.id=p_entity_id and public.is_project_member(n.project_id))
    when 'task' then exists(select 1 from public.tasks t where t.id=p_entity_id and public.is_project_member(t.project_id))
    when 'report' then exists(select 1 from public.reports r where r.id=p_entity_id and public.is_project_member(r.project_id))
    else false end $$;

alter table public.task_dependencies enable row level security; alter table public.material_versions enable row level security; alter table public.material_shares enable row level security; alter table public.tags enable row level security; alter table public.material_tags enable row level security; alter table public.taxonomies enable row level security; alter table public.taxonomy_terms enable row level security; alter table public.material_taxonomy_terms enable row level security; alter table public.reference_collections enable row level security; alter table public.reference_collection_items enable row level security; alter table public.citations_in_use enable row level security; alter table public.comments enable row level security; alter table public.integration_connections enable row level security; alter table public.webhooks enable row level security;

create policy "task dependency by membership" on public.task_dependencies for all to authenticated using(exists(select 1 from public.tasks t where t.id=task_id and public.is_project_member(t.project_id))) with check(exists(select 1 from public.tasks t where t.id=task_id and public.is_project_member(t.project_id)));
create policy "material versions visible with material" on public.material_versions for select to authenticated using(public.can_view_material(material_id)); create policy "material versions write by member" on public.material_versions for insert to authenticated with check(exists(select 1 from public.materials m where m.id=material_id and public.is_project_member(m.project_id)));
create policy "material shares admin managed" on public.material_shares for all to authenticated using(public.is_admin_or_owner()) with check(public.is_admin_or_owner());
create policy "tags by project membership" on public.tags for all to authenticated using(project_id is null or public.is_project_member(project_id)) with check(project_id is null or public.is_project_member(project_id));
create policy "material tags visible with material" on public.material_tags for all to authenticated using(public.can_view_material(material_id)) with check(exists(select 1 from public.materials m where m.id=material_id and public.is_project_member(m.project_id)));
create policy "taxonomies readable" on public.taxonomies for select to authenticated using(true); create policy "taxonomies admin managed" on public.taxonomies for all to authenticated using(public.is_admin_or_owner()) with check(public.is_admin_or_owner());
create policy "taxonomy terms readable" on public.taxonomy_terms for select to authenticated using(true); create policy "taxonomy terms admin managed" on public.taxonomy_terms for all to authenticated using(public.is_admin_or_owner()) with check(public.is_admin_or_owner());
create policy "material terms visible with material" on public.material_taxonomy_terms for all to authenticated using(public.can_view_material(material_id)) with check(exists(select 1 from public.materials m where m.id=material_id and public.is_project_member(m.project_id)));
create policy "collections by membership" on public.reference_collections for all to authenticated using(public.is_project_member(project_id)) with check(public.is_project_member(project_id));
create policy "collection items by membership" on public.reference_collection_items for all to authenticated using(exists(select 1 from public.reference_collections c where c.id=collection_id and public.is_project_member(c.project_id))) with check(exists(select 1 from public.reference_collections c where c.id=collection_id and public.is_project_member(c.project_id)));
create policy "citations by reference membership" on public.citations_in_use for all to authenticated using(exists(select 1 from public.references r where r.id=reference_id and public.is_project_member(r.project_id))) with check(exists(select 1 from public.references r where r.id=reference_id and public.is_project_member(r.project_id)));
create policy "comments scoped to source" on public.comments for all to authenticated using(public.can_view_comment(entity_type,entity_id)) with check(public.can_view_comment(entity_type,entity_id) and author_id=auth.uid());
create policy "own integrations" on public.integration_connections for all to authenticated using(user_id=auth.uid() or public.is_admin_or_owner()) with check(user_id=auth.uid() or public.is_admin_or_owner());
create policy "webhooks admin managed" on public.webhooks for all to authenticated using(public.is_admin_or_owner()) with check(public.is_admin_or_owner());
